pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }
    environment {
        cluster = "vproprod"
        service = "vprofileprodsvc"
    }

    stages{
        stage('DEPLOY APP IMAGE TO ECS PROD'){
            steps{
                withAWS(credentials: 'awscreds', region: 'eu-west-2'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }


    }
}

